-- Optional PostgreSQL deployment migration. The zero-install SQLite adapter
-- owns the local test path; this file is consumed by deployment tooling that
-- injects a PostgreSQL DB-API connection.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS memories (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    category TEXT NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    structured_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    source TEXT NOT NULL,
    source_reference TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    last_accessed_at TIMESTAMPTZ,
    confidence DOUBLE PRECISION NOT NULL,
    sensitivity TEXT NOT NULL,
    scope TEXT NOT NULL,
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    retention_policy TEXT NOT NULL,
    status TEXT NOT NULL,
    supersedes TEXT,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    embedding vector
);
CREATE INDEX IF NOT EXISTS idx_memories_fts ON memories USING GIN (to_tsvector('simple', content));

-- Remaining Phase 03 tables follow the same product-owned records as the
-- SQLite schema and are intentionally generated by deployment migrations.
